POST http://localhost:8080/login
Content-Type: application/json

{
  "email": "francoadesso@gmail.com",
  "password": "000000000"
}

####

POST http://localhost:8080/create
Content-Type: application/json

{ 
  "title": "Test Post",
  "description": "This is a test post",
  "isFeatured":"true"
}

####
POST http://localhost:8080/updateProfileImages
Content-Type: application/json

{
 "path": "https://res.cloudinary.com/dmxpuunwf/image/upload/v1714257434/CamelNetwork/UserProfile/user_undefined_1714257433001.png",
}  
    